package com.sql.antlr3.hive.properties;

public enum Param {
    WITH_COUNT("WITH_COUNT"),
    DISTINCT_COUNT("DISTINCT_COUNT"),
    SELECT_DISTINCT_COUNT("SELECT_DISTINCT_COUNT"),
    INSERT_INTO_COUNT("INSERT_INTO_COUNT"),
    TABLE_COUNT("TABLE_COUNT"),
//    INSERT_OVERWRITE_COUNT("INSERT_OVERWRITE_COUNT"),
    TABNAME_COUNT("TABNAME_COUNT"),
    SELECT_COUNT("SELECT_COUNT"),
    ROW_NUMBER_COUNT("ROW_NUMBER_COUNT"),
    SELECT_COL_COUNT("SELECT_COL_COUNT"),
    XINGHAO_COUNT("XINGHAO_COUNT"),
    FROM_COUNT("FROM_COUNT"),
    SORT_BY_COUNT("SORT_BY_COUNT"),
    ORDER_BY_COUNT("ORDER_BY_COUNT"),
    GROUP_BY_COUNT("GROUP_BY_COUNT"),
    OVER_ORDER_BY_COUNT("OVER_ORDER_BY_COUNT"),
    LEVELS_UNIONALL("LEVELS_UNIONALL"),
    LEVEL_UNIONALL("LEVEL_UNIONALL"),
    JOIN_COUNT("JOIN_COUNT"),
    CROSS_JOIN_COUNT("CROSS_JOIN_COUNT"),
    FULL_OUTER_JOIN_COUNT("FULL_OUTER_JOIN_COUNT"),
    LEFT_SEMI_JOIN_COUNT("LEFT_SEMI_JOIN_COUNT"),
    RIGHT_OUTER_JOIN_COUNT("RIGHT_OUTER_JOIN_COUNT"),
    UNIQUE_JOIN_COUNT("UNIQUE_JOIN_COUNT"),
    LEFT_OUTER_JOIN_COUNT("LEFT_OUTER_JOIN_COUNT"),
    SUBQUERY_COUNT("SUBQUERY_COUNT"),
    SUBJOIN_COUNT("SUBJOIN_COUNT"),
    SUB_LEFT_OUTER_JOIN_COUNT("SUB_LEFT_OUTER_JOIN_COUNT"),
    Aggregate_COUNT("Aggregate_COUNT"),

    DoubleFact("DoubleFact"),
    FACT("DWD"),
    DIM("DIM");


    private final String param;
    Param(String param) {
        this.param=param;
    }
    public String value() {
        return this.param;
    }
}


